serverConfig:
  runmode: debug               # 开发模式, debug, release, test
  addr: :8080                  # HTTP绑定端口

jwtConfig:
  jwtSecret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

# MySQL 数据库相关配置
mysqlConfig:
  host: 127.0.0.1:3306 # MySQL 机器 ip 和端口，默认 127.0.0.1:3306
  username: root # MySQL 用户名(建议授权最小权限集)
  password: 123456 # MySQL 用户密码
  database: douyin_demo # goserver 系统所用的数据库名
  maxIdleConnections: 100 # MySQL 最大空闲连接数，默认 100
  maxOpenConnections: 100 # MySQL 最大打开的连接数，默认 100
  maxConnectionLifeTime: 10 # 空闲连接最大存活时间，默认 10s
  logLevel: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info