info:
  contact: {}
paths:
  /douyin/favorite/action/:
    post:
      parameters:
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 1-点赞，2-取消点赞
        in: query
        name: action_type
        required: true
        type: integer
      responses:
        "200":
          description: '{"status_code":"200","status_msg":""}'
          schema:
            type: string
      summary: 赞操作
      tags:
      - 扩展接口-1
  /douyin/favorite/list/:
    get:
      parameters:
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: '{"status_code":"200","status_msg":""}'
          schema:
            type: string
      summary: 点赞列表
      tags:
      - 扩展接口-1
  /douyin/feed:
    get:
      parameters:
      - description: 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
        in: query
        name: latest_time
        type: integer
      - description: 用户登录状态下设置
        in: query
        name: token
        type: string
      responses:
        "200":
          description: '{"status_code":"200","status_msg":"", "user_id":"", "token":""}'
          schema:
            type: string
      summary: 视频流接口
      tags:
      - 基础接口
  /douyin/publish/action/:
    post:
      parameters:
      - description: 视频数据
        in: formData
        name: data
        required: true
        type: file
      - description: 用户鉴权token
        in: formData
        name: token
        required: true
        type: string
      - description: 视频标题
        in: formData
        name: title
        required: true
        type: string
      responses:
        "200":
          description: '{"status_code":"200","status_msg":"", "user_id":"", "token":""}'
          schema:
            type: string
      summary: 投稿接口
      tags:
      - 基础接口
  /douyin/publish/list/:
    get:
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: '{"status_code":"200","status_msg":"", "user_id":"", "token":""}'
          schema:
            type: string
      summary: 发布列表
      tags:
      - 基础接口
  /douyin/user/:
    get:
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      - description: 用户鉴权token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: '{"status_code":"200","status_msg":"", "user_id":"", "token":""}'
          schema:
            type: string
      summary: 用户信息
      tags:
      - 基础接口
  /douyin/user/login/:
    post:
      parameters:
      - description: 登录用户名
        in: query
        name: username
        required: true
        type: string
      - description: 登录密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"status_code":"200","status_msg":"", "user_id":"", "token":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 基础接口
  /douyin/user/register/:
    post:
      parameters:
      - description: 注册用户名，最长32个字符
        in: query
        name: username
        required: true
        type: string
      - description: 密码，最长32个字符
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"status_code":"200","status_msg":"", "user_id":"", "token":""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 基础接口
swagger: "2.0"
